cc_library(
    name = "species",
    srcs = ["Species.cpp"],
    hdrs = glob(
            ["*.h"],
        ),
    deps = [":attributes"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "attributes",
    srcs = ["Attributes.cpp"],
    hdrs = ["Attributes.h"],
    visibility = ["//visibility:public"],
)